theme: jekyll-theme-minimal
title: Roychan Meliaz
description: Computer Engineer | Software Technology | AI | Robotics
logo: https://github.com/roychanmeliaz/roychanmeliaz.github.io/blob/main/sempro_filtered_scaled_down.jpg?raw=true
show_downloads: false
